#!/usr/bin/env node
/**
 * Generates the expanded mockRecipes.ts with 120 recipes.
 * Run: node scripts/generate-recipes.mjs
 */
import { writeFileSync } from "fs";
import { join } from "path";

const OUT = join(process.cwd(), "src", "data", "mockRecipes.ts");

const recipes = [
  // ========== BREAKFAST (30) ==========
  { id:"recipe-001", name:"High-Protein Veggie Omelette", meal:"breakfast", serv:2, prep:15, style:["healthy","balanced"],
    ing:[["food-002","Eggs",4,"un","protein"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-016","Spinach",0.05,"kg","vegetables"],["food-018","Bell peppers",0.05,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Beat eggs in a bowl with a pinch of salt","Heat olive oil in a non-stick pan over medium heat","Add spinach, tomatoes and peppers, sauté 2 min","Pour eggs over vegetables and cook 5-7 minutes","Fold in half and serve"],
    tags:["quick","high-protein","low-carb"] },
  { id:"recipe-002", name:"Overnight Oats with Berries", meal:"breakfast", serv:1, prep:5, style:["healthy","balanced"],
    ing:[["food-010","Oats",0.08,"kg","grains"],["food-035","Milk (skim)",0.2,"L","dairy"],["food-024","Blueberries",0.05,"kg","fruits"],["food-025","Strawberries",0.05,"kg","fruits"],["food-071","Chia seeds",0.01,"kg","fats"]],
    inst:["Mix oats, milk, and chia seeds in a jar","Refrigerate overnight (8+ hours)","Top with fresh berries before serving"],
    tags:["meal-prep","fiber","no-cook"] },
  { id:"recipe-003", name:"Protein Pancakes", meal:"breakfast", serv:2, prep:20, style:["balanced","comfort"],
    ing:[["food-010","Oats",0.06,"kg","grains"],["food-002","Eggs",3,"un","protein"],["food-022","Banana",1,"un","fruits"],["food-103","Whey protein",0.03,"kg","dairy"],["food-073","Butter",0.01,"kg","fats"]],
    inst:["Blend oats, eggs, banana and protein powder until smooth","Heat butter in a pan over medium heat","Pour small circles of batter","Cook 2 min per side until golden","Serve with fresh fruit"],
    tags:["high-protein","crowd-pleaser","weekend"] },
  { id:"recipe-004", name:"Greek Yogurt Parfait", meal:"breakfast", serv:1, prep:5, style:["healthy"],
    ing:[["food-003","Greek yogurt",0.2,"kg","dairy"],["food-025","Strawberries",0.05,"kg","fruits"],["food-030","Almonds",0.02,"kg","fats"],["food-157","Honey",0.01,"kg","others"]],
    inst:["Layer yogurt in a glass","Add sliced strawberries","Top with almonds and drizzle honey"],
    tags:["quick","no-cook","high-protein"] },
  { id:"recipe-005", name:"Avocado Toast with Eggs", meal:"breakfast", serv:1, prep:10, style:["healthy","balanced"],
    ing:[["food-012","Whole wheat bread",2,"un","grains"],["food-028","Avocado",0.5,"un","fruits"],["food-002","Eggs",2,"un","protein"],["food-027","Olive oil",0.005,"L","fats"]],
    inst:["Toast bread until golden","Mash avocado with salt and lemon","Fry or poach eggs","Spread avocado on toast, top with eggs"],
    tags:["quick","balanced","popular"] },
  { id:"recipe-006", name:"Banana Peanut Butter Smoothie", meal:"breakfast", serv:1, prep:5, style:["balanced","comfort"],
    ing:[["food-022","Banana",1,"un","fruits"],["food-029","Peanut butter",0.02,"kg","fats"],["food-035","Milk (skim)",0.3,"L","dairy"],["food-103","Whey protein",0.03,"kg","dairy"],["food-010","Oats",0.03,"kg","grains"]],
    inst:["Add all ingredients to a blender","Blend until smooth (30 seconds)","Pour and serve immediately"],
    tags:["quick","bulking","liquid-calories"] },
  { id:"recipe-007", name:"Scrambled Eggs with Spinach", meal:"breakfast", serv:2, prep:10, style:["healthy"],
    ing:[["food-002","Eggs",4,"un","protein"],["food-016","Spinach",0.08,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"],["food-097","Mozzarella",0.03,"kg","dairy"]],
    inst:["Heat olive oil in a pan","Add spinach and wilt 1 minute","Pour beaten eggs, stir gently","Add mozzarella, cook until just set"],
    tags:["quick","high-protein","keto-friendly"] },
  { id:"recipe-008", name:"Turkey Breakfast Wrap", meal:"breakfast", serv:1, prep:10, style:["balanced"],
    ing:[["food-046","Whole wheat tortilla",1,"un","grains"],["food-031","Turkey breast",0.08,"kg","protein"],["food-002","Eggs",2,"un","protein"],["food-017","Tomatoes",0.05,"kg","vegetables"],["food-021","Lettuce",0.03,"kg","vegetables"]],
    inst:["Scramble eggs in a pan","Warm tortilla","Layer turkey, eggs, tomatoes and lettuce","Roll tightly and slice in half"],
    tags:["portable","high-protein","meal-prep"] },
  { id:"recipe-009", name:"Cottage Cheese Bowl", meal:"breakfast", serv:1, prep:5, style:["healthy"],
    ing:[["food-007","Cottage cheese",0.2,"kg","dairy"],["food-062","Pineapple",0.08,"kg","fruits"],["food-030","Almonds",0.02,"kg","fats"],["food-070","Flaxseed",0.01,"kg","fats"]],
    inst:["Place cottage cheese in a bowl","Top with pineapple chunks","Sprinkle almonds and flaxseed"],
    tags:["quick","no-cook","high-protein"] },
  { id:"recipe-010", name:"Oatmeal with Banana and Walnuts", meal:"breakfast", serv:1, prep:10, style:["healthy","balanced"],
    ing:[["food-010","Oats",0.08,"kg","grains"],["food-022","Banana",1,"un","fruits"],["food-069","Walnuts",0.02,"kg","fats"],["food-157","Honey",0.01,"kg","others"],["food-035","Milk (skim)",0.2,"L","dairy"]],
    inst:["Cook oats with milk for 5 minutes","Slice banana on top","Add walnuts and drizzle honey"],
    tags:["warm","fiber","heart-healthy"] },
  { id:"recipe-011", name:"Egg Muffin Cups", meal:"breakfast", serv:6, prep:25, style:["healthy","balanced"],
    ing:[["food-002","Eggs",6,"un","protein"],["food-015","Broccoli",0.1,"kg","vegetables"],["food-018","Bell peppers",0.08,"kg","vegetables"],["food-099","Cheddar cheese",0.06,"kg","dairy"]],
    inst:["Preheat oven to 180°C","Whisk eggs and season","Divide vegetables into muffin tin","Pour egg mixture over vegetables","Top with cheese, bake 20 min"],
    tags:["meal-prep","portable","batch-cooking"] },
  { id:"recipe-012", name:"Skyr with Berries and Seeds", meal:"breakfast", serv:1, prep:5, style:["healthy"],
    ing:[["food-096","Skyr",0.2,"kg","dairy"],["food-131","Raspberries",0.05,"kg","fruits"],["food-024","Blueberries",0.05,"kg","fruits"],["food-139","Pumpkin seeds",0.015,"kg","fats"]],
    inst:["Spoon skyr into a bowl","Top with mixed berries","Sprinkle pumpkin seeds"],
    tags:["quick","no-cook","nordic"] },
  { id:"recipe-013", name:"Sweet Potato Hash with Eggs", meal:"breakfast", serv:2, prep:25, style:["healthy","comfort"],
    ing:[["food-011","Sweet potato",0.3,"kg","vegetables"],["food-002","Eggs",3,"un","protein"],["food-018","Bell peppers",0.08,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"]],
    inst:["Dice sweet potato into small cubes","Sauté in olive oil 10-12 min until tender","Add diced peppers, cook 3 min","Make wells, crack eggs in, cover and cook 5 min"],
    tags:["filling","complex-carbs","weekend"] },
  { id:"recipe-014", name:"Protein Shake Bowl", meal:"breakfast", serv:1, prep:5, style:["balanced"],
    ing:[["food-103","Whey protein",0.03,"kg","dairy"],["food-022","Banana",1,"un","fruits"],["food-132","Blueberries (frozen)",0.08,"kg","fruits"],["food-036","Almond milk",0.15,"L","dairy"],["food-010","Oats",0.03,"kg","grains"]],
    inst:["Blend protein, banana, berries and almond milk until thick","Pour into bowl","Top with oats and extra berries"],
    tags:["quick","high-protein","post-workout"] },
  { id:"recipe-015", name:"Smoked Salmon on Rye", meal:"breakfast", serv:1, prep:5, style:["healthy"],
    ing:[["food-045","Rye bread",2,"un","grains"],["food-004","Salmon",0.08,"kg","protein"],["food-100","Cream cheese (light)",0.03,"kg","dairy"],["food-020","Cucumber",0.05,"kg","vegetables"]],
    inst:["Toast rye bread lightly","Spread cream cheese on each slice","Top with smoked salmon and cucumber slices"],
    tags:["omega-3","quick","scandinavian"] },
  { id:"recipe-016", name:"Chia Pudding with Mango", meal:"breakfast", serv:1, prep:5, style:["healthy"],
    ing:[["food-071","Chia seeds",0.03,"kg","fats"],["food-036","Almond milk",0.2,"L","dairy"],["food-065","Mango",0.1,"kg","fruits"],["food-157","Honey",0.01,"kg","others"]],
    inst:["Mix chia seeds with almond milk and honey","Refrigerate overnight","Top with diced mango before serving"],
    tags:["no-cook","meal-prep","vegan-option"] },
  { id:"recipe-017", name:"Tofu Scramble", meal:"breakfast", serv:2, prep:15, style:["healthy"],
    ing:[["food-039","Tofu (firm)",0.2,"kg","protein"],["food-016","Spinach",0.05,"kg","vegetables"],["food-017","Tomatoes",0.08,"kg","vegetables"],["food-156","Turmeric",0.003,"kg","others"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Crumble tofu into small pieces","Heat oil, add turmeric and crumbled tofu","Sauté 5 min until golden","Add spinach and tomatoes, cook 3 min more"],
    tags:["vegan","high-protein","plant-based"] },
  { id:"recipe-018", name:"Granola Energy Bowl", meal:"breakfast", serv:1, prep:5, style:["balanced","comfort"],
    ing:[["food-010","Oats",0.05,"kg","grains"],["food-095","Natural yogurt",0.15,"kg","dairy"],["food-022","Banana",0.5,"un","fruits"],["food-030","Almonds",0.02,"kg","fats"],["food-157","Honey",0.015,"kg","others"]],
    inst:["Layer yogurt in a bowl","Add oats as granola base","Top with sliced banana, almonds, and honey"],
    tags:["quick","energy","balanced"] },
  { id:"recipe-019", name:"Egg and Cheese Sandwich", meal:"breakfast", serv:1, prep:10, style:["comfort","balanced"],
    ing:[["food-012","Whole wheat bread",2,"un","grains"],["food-002","Eggs",2,"un","protein"],["food-099","Cheddar cheese",0.03,"kg","dairy"],["food-073","Butter",0.005,"kg","fats"]],
    inst:["Butter bread and toast in a pan","Fry eggs to desired doneness","Place cheese on warm toast to melt","Assemble sandwich with eggs"],
    tags:["quick","comfort","classic"] },
  { id:"recipe-020", name:"Açaí Bowl with Protein", meal:"breakfast", serv:1, prep:10, style:["healthy"],
    ing:[["food-132","Blueberries (frozen)",0.1,"kg","fruits"],["food-022","Banana",1,"un","fruits"],["food-103","Whey protein",0.025,"kg","dairy"],["food-010","Oats",0.03,"kg","grains"],["food-071","Chia seeds",0.01,"kg","fats"]],
    inst:["Blend frozen berries and banana until thick","Mix in protein powder","Pour into bowl, top with oats and chia seeds"],
    tags:["antioxidant","high-protein","trendy"] },
  { id:"recipe-021", name:"Mushroom and Cheese Omelette", meal:"breakfast", serv:1, prep:12, style:["healthy","balanced"],
    ing:[["food-002","Eggs",3,"un","protein"],["food-056","Mushrooms",0.08,"kg","vegetables"],["food-097","Mozzarella",0.03,"kg","dairy"],["food-027","Olive oil",0.005,"L","fats"]],
    inst:["Sauté sliced mushrooms in olive oil 3 min","Beat eggs and pour over mushrooms","Add mozzarella, cook until set","Fold and serve"],
    tags:["quick","keto-friendly","savory"] },
  { id:"recipe-022", name:"Quinoa Breakfast Bowl", meal:"breakfast", serv:1, prep:20, style:["healthy"],
    ing:[["food-013","Quinoa",0.06,"kg","grains"],["food-035","Milk (skim)",0.15,"L","dairy"],["food-022","Banana",0.5,"un","fruits"],["food-030","Almonds",0.015,"kg","fats"],["food-157","Honey",0.01,"kg","others"]],
    inst:["Cook quinoa in milk until tender (15 min)","Transfer to bowl","Top with banana, almonds and honey"],
    tags:["gluten-free","complete-protein","warm"] },
  { id:"recipe-023", name:"Peanut Butter Banana Toast", meal:"breakfast", serv:1, prep:5, style:["balanced","comfort"],
    ing:[["food-012","Whole wheat bread",2,"un","grains"],["food-029","Peanut butter",0.025,"kg","fats"],["food-022","Banana",1,"un","fruits"]],
    inst:["Toast bread until golden","Spread peanut butter generously","Top with sliced banana"],
    tags:["quick","energy","simple"] },
  { id:"recipe-024", name:"Veggie Frittata", meal:"breakfast", serv:4, prep:30, style:["healthy","balanced"],
    ing:[["food-002","Eggs",6,"un","protein"],["food-049","Zucchini",0.15,"kg","vegetables"],["food-018","Bell peppers",0.1,"kg","vegetables"],["food-098","Parmesan cheese",0.04,"kg","dairy"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Preheat oven to 180°C","Sauté vegetables in olive oil 5 min","Pour beaten eggs with parmesan over veggies","Bake 20 min until set and golden"],
    tags:["meal-prep","batch-cooking","versatile"] },
  { id:"recipe-025", name:"Breakfast Burrito", meal:"breakfast", serv:1, prep:15, style:["comfort","balanced"],
    ing:[["food-046","Whole wheat tortilla",1,"un","grains"],["food-002","Eggs",2,"un","protein"],["food-086","Black beans",0.06,"kg","legumes"],["food-099","Cheddar cheese",0.03,"kg","dairy"],["food-017","Tomatoes",0.05,"kg","vegetables"]],
    inst:["Scramble eggs in a pan","Warm beans and tortilla","Layer eggs, beans, cheese and diced tomato","Roll tightly, optionally toast seam-side down"],
    tags:["filling","portable","fiber"] },
  { id:"recipe-026", name:"Kefir Smoothie with Berries", meal:"breakfast", serv:1, prep:5, style:["healthy"],
    ing:[["food-102","Kefir",0.25,"L","dairy"],["food-025","Strawberries",0.08,"kg","fruits"],["food-022","Banana",0.5,"un","fruits"],["food-070","Flaxseed",0.01,"kg","fats"]],
    inst:["Add all ingredients to blender","Blend until smooth","Serve immediately"],
    tags:["probiotics","gut-health","quick"] },
  { id:"recipe-027", name:"French Toast with Cinnamon", meal:"breakfast", serv:2, prep:15, style:["comfort"],
    ing:[["food-036","White bread",4,"un","grains"],["food-002","Eggs",3,"un","protein"],["food-035","Milk (skim)",0.1,"L","dairy"],["food-073","Butter",0.01,"kg","fats"],["food-157","Honey",0.02,"kg","others"]],
    inst:["Whisk eggs and milk with cinnamon","Dip bread slices in mixture","Cook in butter 2-3 min per side","Serve with honey drizzle"],
    tags:["weekend","comfort","crowd-pleaser"] },
  { id:"recipe-028", name:"Tempeh Breakfast Hash", meal:"breakfast", serv:2, prep:20, style:["healthy"],
    ing:[["food-108","Tempeh",0.15,"kg","protein"],["food-011","Sweet potato",0.2,"kg","vegetables"],["food-018","Bell peppers",0.08,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Dice sweet potato and tempeh into cubes","Sauté sweet potato in oil 8 min","Add tempeh and peppers, cook 5 min more","Season with paprika and serve"],
    tags:["plant-based","filling","vegan"] },
  { id:"recipe-029", name:"Ricotta Toast with Honey and Walnuts", meal:"breakfast", serv:1, prep:5, style:["balanced"],
    ing:[["food-118","Sourdough bread",2,"un","grains"],["food-160","Ricotta",0.06,"kg","dairy"],["food-069","Walnuts",0.02,"kg","fats"],["food-157","Honey",0.01,"kg","others"]],
    inst:["Toast sourdough slices","Spread ricotta generously","Top with walnuts and honey drizzle"],
    tags:["quick","elegant","italian"] },
  { id:"recipe-030", name:"Protein Oat Porridge", meal:"breakfast", serv:1, prep:10, style:["balanced"],
    ing:[["food-010","Oats",0.08,"kg","grains"],["food-103","Whey protein",0.025,"kg","dairy"],["food-035","Milk (skim)",0.25,"L","dairy"],["food-029","Peanut butter",0.015,"kg","fats"],["food-022","Banana",0.5,"un","fruits"]],
    inst:["Cook oats in milk 5 min","Stir in protein powder off heat","Top with peanut butter and sliced banana"],
    tags:["bulking","high-protein","warm"] },

  // ========== LUNCH (30) ==========
  { id:"recipe-031", name:"Grilled Chicken with Rice and Broccoli", meal:"lunch", serv:2, prep:30, style:["healthy","balanced"],
    ing:[["food-001","Chicken breast",0.3,"kg","protein"],["food-009","Brown rice",0.15,"kg","grains"],["food-015","Broccoli",0.2,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Season chicken with salt and pepper","Grill chicken 6-7 min per side","Cook rice according to package","Steam broccoli 5 min, drizzle olive oil"],
    tags:["classic","meal-prep","high-protein"] },
  { id:"recipe-032", name:"Salmon Bowl with Quinoa", meal:"lunch", serv:2, prep:25, style:["healthy"],
    ing:[["food-004","Salmon fillet",0.25,"kg","protein"],["food-013","Quinoa",0.12,"kg","grains"],["food-050","Asparagus",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"],["food-026","Lemon",0.5,"un","fruits"]],
    inst:["Cook quinoa in salted water 15 min","Bake salmon at 200°C for 12 min","Grill asparagus with olive oil","Assemble bowls, squeeze lemon on top"],
    tags:["omega-3","nutrient-dense","meal-prep"] },
  { id:"recipe-033", name:"Turkey and Sweet Potato Plate", meal:"lunch", serv:2, prep:35, style:["healthy","balanced"],
    ing:[["food-031","Turkey breast",0.25,"kg","protein"],["food-011","Sweet potato",0.3,"kg","vegetables"],["food-016","Spinach",0.08,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Slice turkey into medallions and season","Cube sweet potato, roast at 200°C 25 min","Pan-sear turkey 4 min per side","Serve over fresh spinach with olive oil"],
    tags:["lean-protein","complex-carbs","clean"] },
  { id:"recipe-034", name:"Tuna Salad with White Beans", meal:"lunch", serv:2, prep:10, style:["healthy"],
    ing:[["food-005","Tuna (canned)",0.2,"kg","protein"],["food-088","White beans",0.15,"kg","legumes"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"],["food-021","Lettuce",0.08,"kg","vegetables"]],
    inst:["Drain tuna and beans","Dice tomatoes","Combine all on a bed of lettuce","Dress with olive oil, salt and lemon"],
    tags:["no-cook","high-protein","quick"] },
  { id:"recipe-035", name:"Beef Stir-Fry with Vegetables", meal:"lunch", serv:2, prep:20, style:["balanced","comfort"],
    ing:[["food-006","Lean ground beef",0.25,"kg","protein"],["food-018","Bell peppers",0.1,"kg","vegetables"],["food-015","Broccoli",0.15,"kg","vegetables"],["food-008","White rice",0.15,"kg","grains"],["food-152","Soy sauce",0.02,"L","others"]],
    inst:["Cook rice according to package","Brown beef in a hot wok 5 min","Add vegetables, stir-fry 3-4 min","Add soy sauce, serve over rice"],
    tags:["quick","asian-style","balanced"] },
  { id:"recipe-036", name:"Chickpea and Vegetable Curry", meal:"lunch", serv:3, prep:30, style:["healthy","comfort"],
    ing:[["food-085","Chickpeas (canned)",0.25,"kg","legumes"],["food-011","Sweet potato",0.2,"kg","vegetables"],["food-016","Spinach",0.08,"kg","vegetables"],["food-017","Tomatoes",0.15,"kg","vegetables"],["food-072","Coconut oil",0.01,"L","fats"]],
    inst:["Dice sweet potato, sauté in coconut oil 5 min","Add tomatoes and curry spices, simmer 10 min","Add chickpeas and sweet potato, cook 10 min","Stir in spinach until wilted, serve"],
    tags:["vegan","fiber","batch-cooking"] },
  { id:"recipe-037", name:"Cod with Roasted Vegetables", meal:"lunch", serv:2, prep:30, style:["healthy"],
    ing:[["food-032","Cod fillet",0.3,"kg","protein"],["food-049","Zucchini",0.15,"kg","vegetables"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"],["food-018","Bell peppers",0.1,"kg","vegetables"]],
    inst:["Cut vegetables, toss with olive oil, season","Roast vegetables at 200°C for 15 min","Add cod to the tray, bake 12 min more","Serve together with lemon"],
    tags:["low-calorie","lean-protein","mediterranean"] },
  { id:"recipe-038", name:"Lentil Soup with Vegetables", meal:"lunch", serv:4, prep:35, style:["healthy","comfort"],
    ing:[["food-082","Red lentils",0.2,"kg","legumes"],["food-019","Carrots",0.15,"kg","vegetables"],["food-058","Celery",0.08,"kg","vegetables"],["food-017","Tomatoes",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Sauté diced carrots and celery in olive oil 5 min","Add lentils, tomatoes, and 800ml water","Simmer 25 min until lentils are soft","Season with cumin, salt and pepper"],
    tags:["batch-cooking","budget","fiber"] },
  { id:"recipe-039", name:"Chicken Caesar Salad", meal:"lunch", serv:2, prep:20, style:["balanced"],
    ing:[["food-001","Chicken breast",0.25,"kg","protein"],["food-059","Romaine lettuce",0.15,"kg","vegetables"],["food-098","Parmesan",0.03,"kg","dairy"],["food-012","Whole wheat bread",1,"un","grains"],["food-027","Olive oil",0.015,"L","fats"]],
    inst:["Grill seasoned chicken, slice thin","Toast bread cubes for croutons","Toss lettuce with olive oil dressing","Top with chicken, parmesan and croutons"],
    tags:["classic","high-protein","popular"] },
  { id:"recipe-040", name:"Pork Loin with Couscous", meal:"lunch", serv:2, prep:25, style:["balanced"],
    ing:[["food-033","Pork loin",0.25,"kg","protein"],["food-034","Couscous",0.12,"kg","grains"],["food-049","Zucchini",0.12,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Season and sear pork loin 5 min per side","Finish in oven at 180°C for 10 min","Pour boiling water over couscous, cover 5 min","Sauté zucchini, serve alongside sliced pork"],
    tags:["balanced","quick","european"] },
  { id:"recipe-041", name:"Shrimp and Avocado Bowl", meal:"lunch", serv:2, prep:15, style:["healthy"],
    ing:[["food-040","Shrimp",0.2,"kg","protein"],["food-028","Avocado",1,"un","fruits"],["food-008","White rice",0.12,"kg","grains"],["food-020","Cucumber",0.1,"kg","vegetables"],["food-152","Soy sauce",0.015,"L","others"]],
    inst:["Cook rice according to package","Sauté shrimp with garlic 3 min per side","Slice avocado and cucumber","Assemble bowls with rice, shrimp, avocado, cucumber and soy sauce"],
    tags:["light","omega-3","asian-inspired"] },
  { id:"recipe-042", name:"Black Bean and Rice Bowl", meal:"lunch", serv:2, prep:20, style:["healthy","comfort"],
    ing:[["food-086","Black beans",0.2,"kg","legumes"],["food-009","Brown rice",0.15,"kg","grains"],["food-018","Bell peppers",0.1,"kg","vegetables"],["food-028","Avocado",0.5,"un","fruits"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Cook rice","Heat beans with cumin and garlic","Sauté peppers","Assemble bowls; top with sliced avocado"],
    tags:["vegan-option","fiber","latin"] },
  { id:"recipe-043", name:"Mackerel with Roasted Beetroot", meal:"lunch", serv:2, prep:35, style:["healthy"],
    ing:[["food-107","Mackerel fillet",0.25,"kg","protein"],["food-123","Beetroot",0.2,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"],["food-016","Spinach",0.06,"kg","vegetables"]],
    inst:["Wrap beetroot in foil, roast at 200°C 25 min","Pan-sear mackerel skin-side down 4 min, flip 2 min","Slice beetroot","Serve over spinach with olive oil"],
    tags:["omega-3","iron","nutrient-dense"] },
  { id:"recipe-044", name:"Tofu Stir-Fry with Vegetables", meal:"lunch", serv:2, prep:20, style:["healthy"],
    ing:[["food-039","Tofu (firm)",0.25,"kg","protein"],["food-015","Broccoli",0.15,"kg","vegetables"],["food-019","Carrots",0.1,"kg","vegetables"],["food-142","Sesame oil",0.01,"L","fats"],["food-152","Soy sauce",0.02,"L","others"]],
    inst:["Press and cube tofu, fry until golden 5 min","Remove tofu, stir-fry vegetables 4 min","Return tofu, add soy sauce and sesame oil","Serve with rice or noodles"],
    tags:["vegan","plant-based","quick"] },
  { id:"recipe-045", name:"Mediterranean Chicken Wrap", meal:"lunch", serv:2, prep:15, style:["balanced"],
    ing:[["food-001","Chicken breast",0.2,"kg","protein"],["food-046","Whole wheat tortilla",2,"un","grains"],["food-078","Hummus",0.06,"kg","snacks"],["food-017","Tomatoes",0.08,"kg","vegetables"],["food-021","Lettuce",0.05,"kg","vegetables"]],
    inst:["Grill sliced chicken with herbs","Warm tortillas","Spread hummus on each tortilla","Add chicken, tomatoes, lettuce; roll tightly"],
    tags:["portable","quick","mediterranean"] },
  { id:"recipe-046", name:"Egg Fried Rice", meal:"lunch", serv:2, prep:15, style:["comfort","balanced"],
    ing:[["food-008","White rice",0.2,"kg","grains"],["food-002","Eggs",3,"un","protein"],["food-127","Peas (frozen)",0.08,"kg","vegetables"],["food-019","Carrots",0.08,"kg","vegetables"],["food-152","Soy sauce",0.02,"L","others"]],
    inst:["Cook and cool rice (day-old is best)","Scramble eggs, set aside","Stir-fry vegetables 2 min","Add rice and soy sauce, toss with eggs"],
    tags:["quick","budget","asian-style"] },
  { id:"recipe-047", name:"Grilled Tilapia with Salad", meal:"lunch", serv:2, prep:20, style:["healthy"],
    ing:[["food-037","Tilapia fillet",0.3,"kg","protein"],["food-021","Lettuce",0.1,"kg","vegetables"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-020","Cucumber",0.1,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Season tilapia with lemon and herbs","Grill 4 min per side","Prepare salad with lettuce, tomatoes, cucumber","Dress with olive oil and serve alongside fish"],
    tags:["light","low-calorie","cutting"] },
  { id:"recipe-048", name:"Chicken and Pasta Primavera", meal:"lunch", serv:3, prep:25, style:["balanced","comfort"],
    ing:[["food-001","Chicken breast",0.25,"kg","protein"],["food-120","Whole wheat penne",0.2,"kg","grains"],["food-049","Zucchini",0.1,"kg","vegetables"],["food-018","Bell peppers",0.1,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"]],
    inst:["Cook pasta al dente","Grill chicken, slice thin","Sauté vegetables in olive oil 5 min","Toss everything together with herbs"],
    tags:["batch-cooking","italian","balanced"] },
  { id:"recipe-049", name:"Split Pea Soup", meal:"lunch", serv:4, prep:40, style:["healthy","comfort"],
    ing:[["food-089","Split peas",0.2,"kg","legumes"],["food-019","Carrots",0.1,"kg","vegetables"],["food-058","Celery",0.08,"kg","vegetables"],["food-125","Leeks",0.1,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Sauté leeks, carrots, celery 5 min","Add split peas and 1L water","Simmer 35 min until peas dissolve","Season with salt, pepper and cumin"],
    tags:["batch-cooking","budget","filling"] },
  { id:"recipe-050", name:"Sardine and Tomato Toast", meal:"lunch", serv:1, prep:10, style:["healthy"],
    ing:[["food-043","Sardines (canned)",0.12,"kg","protein"],["food-118","Sourdough bread",2,"un","grains"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-027","Olive oil",0.005,"L","fats"]],
    inst:["Toast sourdough bread","Drain sardines, mash lightly","Dice tomatoes","Top toast with sardines, tomatoes, olive oil drizzle"],
    tags:["omega-3","quick","budget"] },
  { id:"recipe-051", name:"Chicken Burrito Bowl", meal:"lunch", serv:2, prep:25, style:["comfort","balanced"],
    ing:[["food-001","Chicken breast",0.25,"kg","protein"],["food-009","Brown rice",0.15,"kg","grains"],["food-086","Black beans",0.1,"kg","legumes"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-028","Avocado",0.5,"un","fruits"]],
    inst:["Grill seasoned chicken, dice","Cook rice and warm beans","Make quick salsa with diced tomatoes","Assemble bowls with everything plus avocado"],
    tags:["popular","filling","balanced"] },
  { id:"recipe-052", name:"Seitan Kebab with Bulgur", meal:"lunch", serv:2, prep:25, style:["healthy"],
    ing:[["food-109","Seitan",0.2,"kg","protein"],["food-114","Bulgur wheat",0.12,"kg","grains"],["food-018","Bell peppers",0.1,"kg","vegetables"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Cube seitan, thread on skewers with peppers","Grill or broil 8-10 min turning once","Soak bulgur in boiling water 10 min","Serve kebabs over bulgur with diced tomatoes"],
    tags:["plant-based","high-protein","middle-eastern"] },
  { id:"recipe-053", name:"Cottage Cheese Stuffed Peppers", meal:"lunch", serv:2, prep:30, style:["healthy","balanced"],
    ing:[["food-018","Bell peppers",3,"un","vegetables"],["food-007","Cottage cheese",0.2,"kg","dairy"],["food-009","Brown rice",0.1,"kg","grains"],["food-016","Spinach",0.06,"kg","vegetables"],["food-098","Parmesan",0.02,"kg","dairy"]],
    inst:["Halve peppers and remove seeds","Mix cottage cheese with cooked rice and spinach","Stuff peppers with mixture","Top with parmesan, bake at 180°C 20 min"],
    tags:["high-protein","creative","meal-prep"] },
  { id:"recipe-054", name:"Trout with Lemon and Herbs", meal:"lunch", serv:2, prep:20, style:["healthy"],
    ing:[["food-111","Trout fillet",0.3,"kg","protein"],["food-050","Asparagus",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"],["food-026","Lemon",1,"un","fruits"]],
    inst:["Season trout with lemon, herbs and olive oil","Bake at 200°C for 12 min","Grill asparagus alongside","Serve with extra lemon wedges"],
    tags:["omega-3","light","european"] },
  { id:"recipe-055", name:"Lamb with Couscous and Vegetables", meal:"lunch", serv:2, prep:30, style:["balanced","comfort"],
    ing:[["food-041","Lamb chops",0.2,"kg","protein"],["food-113","Couscous",0.12,"kg","grains"],["food-019","Carrots",0.1,"kg","vegetables"],["food-049","Zucchini",0.1,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Season lamb with rosemary and garlic","Sear lamb 4 min per side","Prepare couscous with boiling water","Sauté vegetables, serve alongside"],
    tags:["premium-protein","mediterranean","filling"] },
  { id:"recipe-056", name:"Quinoa and Black Bean Salad", meal:"lunch", serv:2, prep:20, style:["healthy"],
    ing:[["food-013","Quinoa",0.12,"kg","grains"],["food-086","Black beans",0.15,"kg","legumes"],["food-047","Corn",0.08,"kg","grains"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Cook and cool quinoa","Combine with drained beans, corn, diced tomatoes","Dress with olive oil and lime juice","Serve cold or at room temperature"],
    tags:["vegan","meal-prep","fiber"] },
  { id:"recipe-057", name:"Chicken Teriyaki with Rice", meal:"lunch", serv:2, prep:20, style:["comfort","balanced"],
    ing:[["food-105","Chicken thigh",0.3,"kg","protein"],["food-008","White rice",0.15,"kg","grains"],["food-152","Soy sauce",0.03,"L","others"],["food-157","Honey",0.02,"kg","others"],["food-015","Broccoli",0.15,"kg","vegetables"]],
    inst:["Mix soy sauce and honey for teriyaki glaze","Cook chicken in pan, add glaze last 3 min","Cook rice and steam broccoli","Serve chicken over rice with broccoli"],
    tags:["asian-style","popular","flavor"] },
  { id:"recipe-058", name:"White Bean and Tuna Salad", meal:"lunch", serv:2, prep:10, style:["healthy"],
    ing:[["food-005","Tuna (canned)",0.15,"kg","protein"],["food-088","White beans",0.2,"kg","legumes"],["food-059","Romaine lettuce",0.1,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"],["food-026","Lemon",0.5,"un","fruits"]],
    inst:["Drain tuna and beans","Toss with lettuce and olive oil","Squeeze lemon over top","Season with salt and pepper"],
    tags:["no-cook","quick","italian"] },
  { id:"recipe-059", name:"Tempeh Buddha Bowl", meal:"lunch", serv:2, prep:25, style:["healthy"],
    ing:[["food-108","Tempeh",0.2,"kg","protein"],["food-009","Brown rice",0.12,"kg","grains"],["food-028","Avocado",0.5,"un","fruits"],["food-019","Carrots",0.1,"kg","vegetables"],["food-053","Kale",0.06,"kg","vegetables"]],
    inst:["Slice and marinate tempeh in soy sauce","Pan-fry tempeh until crispy","Cook rice and massage kale","Assemble bowls with all components"],
    tags:["vegan","plant-based","colorful"] },
  { id:"recipe-060", name:"Ground Turkey Lettuce Wraps", meal:"lunch", serv:2, prep:15, style:["healthy"],
    ing:[["food-031","Turkey breast",0.25,"kg","protein"],["food-059","Romaine lettuce",0.12,"kg","vegetables"],["food-019","Carrots",0.08,"kg","vegetables"],["food-152","Soy sauce",0.02,"L","others"],["food-142","Sesame oil",0.005,"L","fats"]],
    inst:["Cook ground turkey with garlic until browned","Add grated carrots, soy sauce and sesame oil","Separate large lettuce leaves as cups","Spoon mixture into lettuce cups"],
    tags:["low-carb","light","asian-inspired"] },

  // ========== DINNER (30) ==========
  { id:"recipe-061", name:"Baked Salmon with Sweet Potato", meal:"dinner", serv:2, prep:30, style:["healthy","balanced"],
    ing:[["food-004","Salmon fillet",0.3,"kg","protein"],["food-011","Sweet potato",0.3,"kg","vegetables"],["food-015","Broccoli",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Cube sweet potato, roast at 200°C 20 min","Season salmon with herbs","Add salmon to tray, bake 12 min more","Steam broccoli and serve everything together"],
    tags:["omega-3","batch-cooking","meal-prep"] },
  { id:"recipe-062", name:"Lean Beef and Vegetable Stew", meal:"dinner", serv:4, prep:45, style:["comfort","balanced"],
    ing:[["food-006","Lean ground beef",0.4,"kg","protein"],["food-019","Carrots",0.15,"kg","vegetables"],["food-011","Sweet potato",0.2,"kg","vegetables"],["food-017","Tomatoes",0.2,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Brown beef in olive oil 5 min","Add diced carrots and sweet potato","Add tomatoes and 500ml water","Simmer 35 min until everything is tender"],
    tags:["batch-cooking","comfort","filling"] },
  { id:"recipe-063", name:"Grilled Chicken Thighs with Green Beans", meal:"dinner", serv:2, prep:25, style:["balanced"],
    ing:[["food-105","Chicken thigh",0.3,"kg","protein"],["food-051","Green beans",0.2,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"],["food-098","Parmesan",0.02,"kg","dairy"]],
    inst:["Season chicken thighs with herbs","Grill 7 min per side","Steam green beans until tender-crisp","Toss beans with olive oil, serve with chicken"],
    tags:["simple","flavorful","balanced"] },
  { id:"recipe-064", name:"Cod with Mashed Sweet Potato", meal:"dinner", serv:2, prep:30, style:["healthy"],
    ing:[["food-106","Cod fillet",0.3,"kg","protein"],["food-011","Sweet potato",0.3,"kg","vegetables"],["food-016","Spinach",0.08,"kg","vegetables"],["food-073","Butter",0.01,"kg","fats"]],
    inst:["Boil sweet potato, mash with butter","Season and bake cod at 200°C 12 min","Wilt spinach in a hot pan","Serve cod over mash with spinach"],
    tags:["lean-protein","comfort","nutritious"] },
  { id:"recipe-065", name:"Turkey Meatballs with Pasta", meal:"dinner", serv:3, prep:35, style:["comfort","balanced"],
    ing:[["food-031","Turkey breast",0.3,"kg","protein"],["food-120","Whole wheat penne",0.2,"kg","grains"],["food-017","Tomatoes",0.2,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"],["food-098","Parmesan",0.03,"kg","dairy"]],
    inst:["Mix ground turkey with herbs, form meatballs","Brown meatballs in olive oil 8 min","Simmer in crushed tomatoes 15 min","Cook pasta, serve with meatballs and parmesan"],
    tags:["batch-cooking","crowd-pleaser","italian"] },
  { id:"recipe-066", name:"Baked Pork Loin with Vegetables", meal:"dinner", serv:2, prep:35, style:["balanced"],
    ing:[["food-104","Pork tenderloin",0.3,"kg","protein"],["food-019","Carrots",0.15,"kg","vegetables"],["food-052","Brussels sprouts",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Season pork with rosemary and garlic","Sear in pan 3 min per side","Toss vegetables with olive oil","Roast pork and vegetables at 200°C 20 min"],
    tags:["lean","roasted","european"] },
  { id:"recipe-067", name:"Shrimp and Vegetable Stir-Fry", meal:"dinner", serv:2, prep:15, style:["healthy"],
    ing:[["food-040","Shrimp",0.25,"kg","protein"],["food-015","Broccoli",0.15,"kg","vegetables"],["food-018","Bell peppers",0.1,"kg","vegetables"],["food-142","Sesame oil",0.01,"L","fats"],["food-152","Soy sauce",0.02,"L","others"]],
    inst:["Heat sesame oil in a wok","Stir-fry shrimp 2 min per side, set aside","Add vegetables, stir-fry 3-4 min","Return shrimp, add soy sauce, toss and serve"],
    tags:["quick","low-calorie","asian-style"] },
  { id:"recipe-068", name:"Vegetarian Chili", meal:"dinner", serv:4, prep:40, style:["healthy","comfort"],
    ing:[["food-087","Kidney beans",0.2,"kg","legumes"],["food-086","Black beans",0.2,"kg","legumes"],["food-017","Tomatoes",0.3,"kg","vegetables"],["food-018","Bell peppers",0.15,"kg","vegetables"],["food-047","Corn",0.1,"kg","grains"]],
    inst:["Sauté peppers 5 min","Add tomatoes, beans and corn","Add cumin, paprika, chili powder","Simmer 30 min, stirring occasionally"],
    tags:["vegan","batch-cooking","fiber"] },
  { id:"recipe-069", name:"Duck Breast with Roasted Vegetables", meal:"dinner", serv:2, prep:30, style:["balanced"],
    ing:[["food-042","Duck breast",0.3,"kg","protein"],["food-011","Sweet potato",0.2,"kg","vegetables"],["food-052","Brussels sprouts",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Score duck skin in a crosshatch pattern","Cook skin-side down in cold pan, render fat 8 min","Flip, cook 4 min more","Roast vegetables in duck fat, serve sliced"],
    tags:["premium","flavor","special-occasion"] },
  { id:"recipe-070", name:"Lentil and Spinach Stew", meal:"dinner", serv:3, prep:30, style:["healthy"],
    ing:[["food-083","Green lentils",0.2,"kg","legumes"],["food-016","Spinach",0.1,"kg","vegetables"],["food-019","Carrots",0.1,"kg","vegetables"],["food-017","Tomatoes",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Sauté diced carrots in olive oil 5 min","Add lentils, tomatoes and 600ml water","Simmer 25 min until lentils tender","Stir in spinach, cook 2 min more"],
    tags:["vegan","iron","budget"] },
  { id:"recipe-071", name:"Herb-Crusted Chicken with Quinoa", meal:"dinner", serv:2, prep:30, style:["healthy","balanced"],
    ing:[["food-001","Chicken breast",0.3,"kg","protein"],["food-013","Quinoa",0.12,"kg","grains"],["food-050","Asparagus",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"],["food-098","Parmesan",0.02,"kg","dairy"]],
    inst:["Mix parmesan with herbs, press onto chicken","Bake at 200°C for 18-20 min","Cook quinoa in salted water 15 min","Grill asparagus, serve alongside"],
    tags:["high-protein","elegant","meal-prep"] },
  { id:"recipe-072", name:"Baked Tilapia with Cauliflower Rice", meal:"dinner", serv:2, prep:20, style:["healthy"],
    ing:[["food-037","Tilapia fillet",0.3,"kg","protein"],["food-048","Cauliflower",0.3,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"],["food-016","Spinach",0.06,"kg","vegetables"]],
    inst:["Pulse cauliflower in food processor to rice texture","Sauté cauliflower rice in olive oil 5 min","Season and bake tilapia at 180°C 12 min","Serve fish over cauliflower rice with spinach"],
    tags:["low-carb","lean","cutting"] },
  { id:"recipe-073", name:"Egg and Vegetable Curry", meal:"dinner", serv:2, prep:25, style:["comfort"],
    ing:[["food-002","Eggs",4,"un","protein"],["food-017","Tomatoes",0.15,"kg","vegetables"],["food-016","Spinach",0.08,"kg","vegetables"],["food-072","Coconut oil",0.01,"L","fats"],["food-008","White rice",0.15,"kg","grains"]],
    inst:["Hard-boil eggs, halve them","Make curry sauce with tomatoes and spices","Add halved eggs and spinach to sauce","Serve over cooked rice"],
    tags:["vegetarian","budget","indian-style"] },
  { id:"recipe-074", name:"Salmon Teriyaki with Edamame", meal:"dinner", serv:2, prep:20, style:["balanced"],
    ing:[["food-004","Salmon fillet",0.25,"kg","protein"],["food-079","Edamame",0.1,"kg","snacks"],["food-008","White rice",0.15,"kg","grains"],["food-152","Soy sauce",0.03,"L","others"],["food-157","Honey",0.02,"kg","others"]],
    inst:["Make teriyaki glaze: soy sauce + honey + ginger","Pan-sear salmon skin-down 4 min, flip 3 min","Glaze salmon in last minute","Serve with rice and steamed edamame"],
    tags:["omega-3","japanese-style","popular"] },
  { id:"recipe-075", name:"Stuffed Eggplant with Lentils", meal:"dinner", serv:2, prep:35, style:["healthy"],
    ing:[["food-057","Eggplant",2,"un","vegetables"],["food-082","Red lentils",0.1,"kg","legumes"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-097","Mozzarella",0.06,"kg","dairy"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Halve eggplant, scoop out centers","Cook lentils with tomatoes 15 min","Fill eggplant shells with lentil mixture","Top with mozzarella, bake at 180°C 20 min"],
    tags:["vegetarian","creative","mediterranean"] },
  { id:"recipe-076", name:"Beef Steak with Sweet Potato Wedges", meal:"dinner", serv:2, prep:30, style:["comfort","balanced"],
    ing:[["food-006","Lean beef",0.25,"kg","protein"],["food-011","Sweet potato",0.3,"kg","vegetables"],["food-016","Spinach",0.06,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"]],
    inst:["Cut sweet potatoes into wedges","Toss with olive oil, bake at 200°C 25 min","Season and sear steak 4 min per side","Rest 5 min, slice and serve with wedges and spinach"],
    tags:["high-protein","filling","popular"] },
  { id:"recipe-077", name:"Chicken and Mushroom Risotto", meal:"dinner", serv:3, prep:35, style:["comfort","balanced"],
    ing:[["food-001","Chicken breast",0.25,"kg","protein"],["food-056","Mushrooms",0.15,"kg","vegetables"],["food-008","White rice",0.2,"kg","grains"],["food-098","Parmesan",0.03,"kg","dairy"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Sauté mushrooms in olive oil 5 min","Add rice, stir 1 min","Add warm broth gradually, stirring 18-20 min","While risotto cooks, grill chicken; stir in parmesan"],
    tags:["italian","comfort","crowd-pleaser"] },
  { id:"recipe-078", name:"Baked Sardines with Potatoes", meal:"dinner", serv:2, prep:30, style:["healthy"],
    ing:[["food-043","Sardines",0.2,"kg","protein"],["food-011","Sweet potato",0.25,"kg","vegetables"],["food-017","Tomatoes",0.1,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"]],
    inst:["Slice potatoes thin, layer in baking dish","Top with tomato slices","Lay sardines on top, drizzle olive oil","Bake at 200°C 25 min"],
    tags:["portuguese","omega-3","budget"] },
  { id:"recipe-079", name:"Cauliflower and Chickpea Bake", meal:"dinner", serv:3, prep:35, style:["healthy"],
    ing:[["food-048","Cauliflower",0.3,"kg","vegetables"],["food-085","Chickpeas",0.2,"kg","legumes"],["food-017","Tomatoes",0.15,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"],["food-156","Turmeric",0.003,"kg","others"]],
    inst:["Cut cauliflower into florets","Toss cauliflower and chickpeas with olive oil and turmeric","Add tomatoes to baking dish","Roast at 200°C 25-30 min"],
    tags:["vegan","fiber","anti-inflammatory"] },
  { id:"recipe-080", name:"Pork Stir-Fry with Rice Noodles", meal:"dinner", serv:2, prep:20, style:["comfort"],
    ing:[["food-033","Pork loin",0.2,"kg","protein"],["food-015","Broccoli",0.12,"kg","vegetables"],["food-019","Carrots",0.08,"kg","vegetables"],["food-008","White rice",0.15,"kg","grains"],["food-152","Soy sauce",0.02,"L","others"]],
    inst:["Slice pork thin, marinate in soy sauce","Cook rice noodles or rice","Stir-fry pork 3 min, add vegetables 3 min","Serve over noodles with soy sauce"],
    tags:["quick","asian-style","balanced"] },
  { id:"recipe-081", name:"Salmon and Avocado Poke Bowl", meal:"dinner", serv:2, prep:15, style:["healthy"],
    ing:[["food-004","Salmon fillet",0.25,"kg","protein"],["food-008","White rice",0.15,"kg","grains"],["food-028","Avocado",1,"un","fruits"],["food-020","Cucumber",0.1,"kg","vegetables"],["food-152","Soy sauce",0.02,"L","others"]],
    inst:["Cook sushi rice and cool","Cube fresh salmon (sashimi grade)","Slice avocado and cucumber","Assemble bowls with rice, fish, veggies; drizzle soy sauce"],
    tags:["japanese","omega-3","trendy"] },
  { id:"recipe-082", name:"Chicken and Bean Casserole", meal:"dinner", serv:4, prep:40, style:["comfort","balanced"],
    ing:[["food-105","Chicken thigh",0.4,"kg","protein"],["food-088","White beans",0.2,"kg","legumes"],["food-017","Tomatoes",0.2,"kg","vegetables"],["food-019","Carrots",0.15,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Brown chicken in olive oil","Add carrots, cook 3 min","Add tomatoes, beans and herbs","Cover and bake at 180°C 30 min"],
    tags:["batch-cooking","one-pot","family"] },
  { id:"recipe-083", name:"Veggie Pad Thai with Tofu", meal:"dinner", serv:2, prep:25, style:["healthy","comfort"],
    ing:[["food-039","Tofu (firm)",0.2,"kg","protein"],["food-019","Carrots",0.1,"kg","vegetables"],["food-018","Bell peppers",0.1,"kg","vegetables"],["food-146","Peanuts",0.03,"kg","snacks"],["food-152","Soy sauce",0.02,"L","others"]],
    inst:["Press and cube tofu, fry until golden","Stir-fry julienned vegetables 3 min","Add rice noodles and soy sauce","Top with crushed peanuts"],
    tags:["vegan","thai-style","popular"] },
  { id:"recipe-084", name:"Mediterranean Baked Chicken", meal:"dinner", serv:2, prep:35, style:["healthy","balanced"],
    ing:[["food-001","Chicken breast",0.3,"kg","protein"],["food-017","Tomatoes",0.15,"kg","vegetables"],["food-049","Zucchini",0.12,"kg","vegetables"],["food-027","Olive oil",0.015,"L","fats"],["food-097","Mozzarella",0.05,"kg","dairy"]],
    inst:["Place chicken in baking dish","Top with sliced tomatoes and zucchini","Drizzle olive oil, add herbs","Add mozzarella, bake at 180°C 25 min"],
    tags:["one-pan","mediterranean","easy"] },
  { id:"recipe-085", name:"Kidney Bean and Sweet Potato Curry", meal:"dinner", serv:3, prep:30, style:["healthy","comfort"],
    ing:[["food-087","Kidney beans",0.2,"kg","legumes"],["food-011","Sweet potato",0.25,"kg","vegetables"],["food-016","Spinach",0.08,"kg","vegetables"],["food-072","Coconut oil",0.01,"L","fats"],["food-009","Brown rice",0.15,"kg","grains"]],
    inst:["Cube sweet potato, sauté in coconut oil 5 min","Add curry paste and kidney beans","Add 200ml water, simmer 20 min","Stir in spinach, serve over brown rice"],
    tags:["vegan","batch-cooking","spicy"] },
  { id:"recipe-086", name:"Grilled Lamb with Minted Peas", meal:"dinner", serv:2, prep:25, style:["balanced"],
    ing:[["food-041","Lamb chops",0.25,"kg","protein"],["food-127","Peas (frozen)",0.15,"kg","vegetables"],["food-011","Sweet potato",0.2,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Season lamb with rosemary, grill 5 min per side","Boil peas, crush with mint and olive oil","Roast sweet potato wedges","Serve lamb with minted peas and wedges"],
    tags:["premium","british","elegant"] },
  { id:"recipe-087", name:"Egg-Drop Soup with Spinach", meal:"dinner", serv:2, prep:15, style:["healthy"],
    ing:[["food-002","Eggs",3,"un","protein"],["food-016","Spinach",0.08,"kg","vegetables"],["food-019","Carrots",0.06,"kg","vegetables"],["food-152","Soy sauce",0.01,"L","others"]],
    inst:["Bring 600ml broth to boil","Add grated carrots and spinach","Slowly drizzle beaten eggs while stirring","Season with soy sauce and serve"],
    tags:["light","quick","low-calorie"] },
  { id:"recipe-088", name:"Chicken Fajita Bowl", meal:"dinner", serv:2, prep:20, style:["comfort","balanced"],
    ing:[["food-001","Chicken breast",0.25,"kg","protein"],["food-018","Bell peppers",0.15,"kg","vegetables"],["food-009","Brown rice",0.12,"kg","grains"],["food-028","Avocado",0.5,"un","fruits"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Slice chicken and peppers into strips","Sauté with fajita spices 8 min","Cook rice separately","Assemble bowls with rice, fajita mix and avocado"],
    tags:["mexican-style","popular","flavorful"] },
  { id:"recipe-089", name:"Canned Salmon Patties", meal:"dinner", serv:2, prep:20, style:["balanced","comfort"],
    ing:[["food-112","Canned salmon",0.2,"kg","protein"],["food-002","Eggs",1,"un","protein"],["food-010","Oats",0.03,"kg","grains"],["food-027","Olive oil",0.01,"L","fats"],["food-021","Lettuce",0.06,"kg","vegetables"]],
    inst:["Drain salmon, mix with egg and oats","Form into patties","Fry in olive oil 4 min per side","Serve on lettuce with lemon"],
    tags:["budget","omega-3","creative"] },
  { id:"recipe-090", name:"One-Pot Chicken and Rice", meal:"dinner", serv:3, prep:35, style:["comfort","balanced"],
    ing:[["food-105","Chicken thigh",0.35,"kg","protein"],["food-008","White rice",0.2,"kg","grains"],["food-019","Carrots",0.1,"kg","vegetables"],["food-127","Peas (frozen)",0.08,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Brown chicken in olive oil, remove","Sauté carrots 3 min, add rice and stir","Add 400ml broth, return chicken","Cover, simmer 20 min until rice is done, add peas last 3 min"],
    tags:["one-pot","family","easy"] },

  // ========== SNACKS (30) ==========
  { id:"recipe-091", name:"Protein Energy Balls", meal:"snack", serv:12, prep:15, style:["healthy","balanced"],
    ing:[["food-010","Oats",0.1,"kg","grains"],["food-029","Peanut butter",0.06,"kg","fats"],["food-157","Honey",0.03,"kg","others"],["food-103","Whey protein",0.03,"kg","dairy"],["food-076","Dark chocolate",0.03,"kg","snacks"]],
    inst:["Mix oats, peanut butter, honey and protein powder","Fold in chopped dark chocolate","Roll into 12 balls","Refrigerate 30 min before serving"],
    tags:["meal-prep","portable","no-bake"] },
  { id:"recipe-092", name:"Greek Yogurt with Honey and Walnuts", meal:"snack", serv:1, prep:3, style:["healthy"],
    ing:[["food-003","Greek yogurt",0.15,"kg","dairy"],["food-069","Walnuts",0.02,"kg","fats"],["food-157","Honey",0.01,"kg","others"]],
    inst:["Spoon yogurt into bowl","Top with walnuts","Drizzle honey"],
    tags:["quick","no-cook","classic"] },
  { id:"recipe-093", name:"Hummus with Veggie Sticks", meal:"snack", serv:2, prep:5, style:["healthy"],
    ing:[["food-078","Hummus",0.1,"kg","snacks"],["food-019","Carrots",0.1,"kg","vegetables"],["food-020","Cucumber",0.1,"kg","vegetables"],["food-018","Bell peppers",0.08,"kg","vegetables"]],
    inst:["Cut vegetables into sticks","Portion hummus into a bowl","Serve together as dip plate"],
    tags:["no-cook","fiber","portable"] },
  { id:"recipe-094", name:"Apple Slices with Peanut Butter", meal:"snack", serv:1, prep:3, style:["balanced"],
    ing:[["food-023","Apple",1,"un","fruits"],["food-029","Peanut butter",0.02,"kg","fats"]],
    inst:["Core and slice apple","Serve with peanut butter for dipping"],
    tags:["quick","simple","classic"] },
  { id:"recipe-095", name:"Cottage Cheese with Pineapple", meal:"snack", serv:1, prep:3, style:["healthy"],
    ing:[["food-007","Cottage cheese",0.15,"kg","dairy"],["food-062","Pineapple",0.08,"kg","fruits"]],
    inst:["Spoon cottage cheese into bowl","Top with pineapple chunks"],
    tags:["quick","high-protein","sweet"] },
  { id:"recipe-096", name:"Trail Mix Energy Portion", meal:"snack", serv:1, prep:2, style:["balanced"],
    ing:[["food-030","Almonds",0.02,"kg","fats"],["food-136","Cranberries (dried)",0.015,"kg","fruits"],["food-076","Dark chocolate",0.01,"kg","snacks"],["food-139","Pumpkin seeds",0.01,"kg","fats"]],
    inst:["Combine all ingredients in a small bag or container","Portion to about 55g total"],
    tags:["portable","no-cook","energy"] },
  { id:"recipe-097", name:"Rice Cakes with Almond Butter", meal:"snack", serv:1, prep:3, style:["balanced"],
    ing:[["food-075","Rice cakes",2,"un","snacks"],["food-141","Almond butter",0.02,"kg","fats"],["food-022","Banana",0.5,"un","fruits"]],
    inst:["Spread almond butter on rice cakes","Top with sliced banana"],
    tags:["quick","gluten-free","crunchy"] },
  { id:"recipe-098", name:"Edamame with Sea Salt", meal:"snack", serv:1, prep:5, style:["healthy"],
    ing:[["food-079","Edamame",0.1,"kg","snacks"]],
    inst:["Steam or microwave edamame 3 min","Sprinkle with sea salt","Eat by squeezing beans from pods"],
    tags:["high-protein","plant-based","quick"] },
  { id:"recipe-099", name:"Banana Oat Cookies", meal:"snack", serv:12, prep:20, style:["healthy","comfort"],
    ing:[["food-022","Banana",2,"un","fruits"],["food-010","Oats",0.12,"kg","grains"],["food-076","Dark chocolate",0.03,"kg","snacks"],["food-071","Chia seeds",0.01,"kg","fats"]],
    inst:["Mash bananas, mix with oats and chia seeds","Fold in chopped dark chocolate","Drop spoonfuls onto lined baking sheet","Bake at 180°C for 12-15 min"],
    tags:["2-ingredient-base","meal-prep","no-sugar-added"] },
  { id:"recipe-100", name:"Protein Shake (Classic)", meal:"snack", serv:1, prep:3, style:["balanced"],
    ing:[["food-103","Whey protein",0.03,"kg","dairy"],["food-035","Milk (skim)",0.3,"L","dairy"],["food-022","Banana",0.5,"un","fruits"]],
    inst:["Add protein, milk and banana to shaker or blender","Shake or blend until smooth","Drink immediately"],
    tags:["post-workout","quick","high-protein"] },
  { id:"recipe-101", name:"Tuna-Stuffed Cucumber Bites", meal:"snack", serv:2, prep:10, style:["healthy"],
    ing:[["food-005","Tuna (canned)",0.1,"kg","protein"],["food-020","Cucumber",1,"un","vegetables"],["food-100","Cream cheese (light)",0.03,"kg","dairy"]],
    inst:["Cut cucumber into 2cm thick rounds","Mix tuna with cream cheese","Spoon mixture onto cucumber rounds"],
    tags:["low-carb","high-protein","finger-food"] },
  { id:"recipe-102", name:"Dark Chocolate and Almond Clusters", meal:"snack", serv:6, prep:15, style:["comfort"],
    ing:[["food-076","Dark chocolate",0.06,"kg","snacks"],["food-030","Almonds",0.04,"kg","fats"]],
    inst:["Melt dark chocolate in microwave 60 sec","Stir in whole almonds","Drop clusters onto parchment paper","Refrigerate 20 min"],
    tags:["sweet","antioxidant","treat"] },
  { id:"recipe-103", name:"Kefir Smoothie with Berry Mix", meal:"snack", serv:1, prep:5, style:["healthy"],
    ing:[["food-102","Kefir",0.2,"L","dairy"],["food-131","Raspberries",0.05,"kg","fruits"],["food-132","Blueberries (frozen)",0.05,"kg","fruits"],["food-157","Honey",0.01,"kg","others"]],
    inst:["Combine kefir, berries and honey in blender","Blend until smooth","Serve immediately"],
    tags:["probiotics","antioxidant","gut-health"] },
  { id:"recipe-104", name:"Egg White Mini Frittatas", meal:"snack", serv:6, prep:20, style:["healthy"],
    ing:[["food-110","Egg whites",0.2,"kg","protein"],["food-016","Spinach",0.06,"kg","vegetables"],["food-017","Tomatoes",0.06,"kg","vegetables"],["food-097","Mozzarella",0.04,"kg","dairy"]],
    inst:["Preheat oven to 180°C","Divide spinach and tomatoes into muffin tins","Pour egg whites over","Top with mozzarella, bake 15 min"],
    tags:["meal-prep","low-calorie","high-protein"] },
  { id:"recipe-105", name:"Frozen Banana Bites", meal:"snack", serv:4, prep:10, style:["comfort"],
    ing:[["food-022","Banana",2,"un","fruits"],["food-076","Dark chocolate",0.05,"kg","snacks"],["food-068","Cashews",0.02,"kg","fats"]],
    inst:["Slice bananas into rounds","Insert toothpick in each","Dip in melted chocolate, sprinkle crushed cashews","Freeze 1 hour"],
    tags:["sweet","frozen-treat","kid-friendly"] },
  { id:"recipe-106", name:"Popcorn with Nutritional Seasoning", meal:"snack", serv:2, prep:5, style:["balanced"],
    ing:[["food-081","Popcorn (air-popped)",0.06,"kg","snacks"],["food-027","Olive oil",0.005,"L","fats"]],
    inst:["Air-pop popcorn kernels","Drizzle lightly with olive oil","Season with salt and nutritional yeast"],
    tags:["high-volume","low-calorie","movie-night"] },
  { id:"recipe-107", name:"Skyr with Date and Almond", meal:"snack", serv:1, prep:3, style:["healthy"],
    ing:[["food-096","Skyr",0.15,"kg","dairy"],["food-133","Dried dates",0.02,"kg","fruits"],["food-030","Almonds",0.015,"kg","fats"]],
    inst:["Place skyr in bowl","Chop dates and sprinkle on top","Add almonds"],
    tags:["high-protein","quick","scandinavian"] },
  { id:"recipe-108", name:"Seaweed Snack with Rice Cake", meal:"snack", serv:1, prep:2, style:["healthy"],
    ing:[["food-147","Seaweed snacks",0.01,"kg","snacks"],["food-075","Rice cakes",1,"un","snacks"]],
    inst:["Layer seaweed sheets on rice cake","Eat as a crispy light snack"],
    tags:["low-calorie","mineral-rich","asian"] },
  { id:"recipe-109", name:"Peanut Butter Banana Roll-Up", meal:"snack", serv:1, prep:3, style:["comfort","balanced"],
    ing:[["food-046","Whole wheat tortilla",1,"un","grains"],["food-029","Peanut butter",0.02,"kg","fats"],["food-022","Banana",1,"un","fruits"]],
    inst:["Spread peanut butter over tortilla","Place whole banana on edge","Roll tightly and slice into rounds"],
    tags:["portable","quick","energy"] },
  { id:"recipe-110", name:"Quark with Mixed Berries", meal:"snack", serv:1, prep:3, style:["healthy"],
    ing:[["food-101","Quark",0.15,"kg","dairy"],["food-025","Strawberries",0.04,"kg","fruits"],["food-131","Raspberries",0.04,"kg","fruits"]],
    inst:["Place quark in bowl","Top with sliced strawberries and raspberries"],
    tags:["high-protein","no-cook","european"] },
  { id:"recipe-111", name:"Sweet Potato Chips (Baked)", meal:"snack", serv:2, prep:30, style:["comfort"],
    ing:[["food-011","Sweet potato",0.25,"kg","vegetables"],["food-027","Olive oil",0.01,"L","fats"]],
    inst:["Slice sweet potato very thin","Toss with olive oil and salt","Bake at 180°C 20-25 min, flipping halfway","Cool until crispy"],
    tags:["healthy-swap","crunchy","meal-prep"] },
  { id:"recipe-112", name:"Tahini Date Balls", meal:"snack", serv:10, prep:15, style:["healthy"],
    ing:[["food-137","Tahini",0.04,"kg","fats"],["food-133","Dried dates",0.06,"kg","fruits"],["food-010","Oats",0.05,"kg","grains"],["food-071","Chia seeds",0.01,"kg","fats"]],
    inst:["Blend dates into a paste","Mix with tahini, oats and chia seeds","Roll into 10 small balls","Refrigerate 30 min"],
    tags:["vegan","no-bake","energy"] },
  { id:"recipe-113", name:"Beef Jerky with Cucumber", meal:"snack", serv:1, prep:2, style:["balanced"],
    ing:[["food-077","Beef jerky",0.04,"kg","snacks"],["food-020","Cucumber",0.1,"kg","vegetables"]],
    inst:["Slice cucumber into sticks","Enjoy with beef jerky"],
    tags:["high-protein","portable","no-cook"] },
  { id:"recipe-114", name:"Chia Pudding Snack Cup", meal:"snack", serv:1, prep:5, style:["healthy"],
    ing:[["food-071","Chia seeds",0.025,"kg","fats"],["food-158","Oat milk",0.15,"L","dairy"],["food-065","Mango",0.06,"kg","fruits"]],
    inst:["Mix chia seeds with oat milk","Refrigerate 2+ hours","Top with diced mango"],
    tags:["meal-prep","vegan","omega-3"] },
  { id:"recipe-115", name:"Protein Bar Smoothie", meal:"snack", serv:1, prep:5, style:["balanced"],
    ing:[["food-074","Protein bar",0.5,"un","snacks"],["food-035","Milk (skim)",0.25,"L","dairy"],["food-022","Banana",0.5,"un","fruits"]],
    inst:["Break protein bar into pieces","Blend with milk and banana","Serve immediately"],
    tags:["post-workout","creative","high-protein"] },
  { id:"recipe-116", name:"Walnuts and Dark Chocolate", meal:"snack", serv:1, prep:1, style:["healthy"],
    ing:[["food-069","Walnuts",0.025,"kg","fats"],["food-076","Dark chocolate",0.015,"kg","snacks"]],
    inst:["Portion walnuts and chocolate squares","Enjoy as an antioxidant-rich snack"],
    tags:["brain-food","quick","no-cook"] },
  { id:"recipe-117", name:"Smashed Chickpea Toast", meal:"snack", serv:1, prep:5, style:["healthy"],
    ing:[["food-085","Chickpeas (canned)",0.08,"kg","legumes"],["food-012","Whole wheat bread",1,"un","grains"],["food-027","Olive oil",0.005,"L","fats"]],
    inst:["Drain and roughly mash chickpeas with fork","Season with olive oil, salt, pepper and lemon","Spread on toasted bread"],
    tags:["vegan","fiber","simple"] },
  { id:"recipe-118", name:"Hemp Seed Yogurt Bowl", meal:"snack", serv:1, prep:3, style:["healthy"],
    ing:[["food-095","Natural yogurt",0.15,"kg","dairy"],["food-140","Hemp seeds",0.015,"kg","fats"],["food-024","Blueberries",0.04,"kg","fruits"]],
    inst:["Place yogurt in bowl","Top with blueberries and hemp seeds"],
    tags:["omega-3","protein","quick"] },
  { id:"recipe-119", name:"Mango Lassi Protein Shake", meal:"snack", serv:1, prep:5, style:["balanced","comfort"],
    ing:[["food-065","Mango",0.1,"kg","fruits"],["food-095","Natural yogurt",0.15,"kg","dairy"],["food-103","Whey protein",0.025,"kg","dairy"],["food-035","Milk (skim)",0.1,"L","dairy"]],
    inst:["Blend mango, yogurt, protein powder and milk","Add ice if desired","Serve immediately"],
    tags:["indian-style","refreshing","high-protein"] },
  { id:"recipe-120", name:"Oat Bar Bites", meal:"snack", serv:8, prep:25, style:["balanced"],
    ing:[["food-010","Oats",0.15,"kg","grains"],["food-157","Honey",0.04,"kg","others"],["food-029","Peanut butter",0.04,"kg","fats"],["food-138","Sunflower seeds",0.02,"kg","fats"],["food-076","Dark chocolate",0.03,"kg","snacks"]],
    inst:["Mix oats, peanut butter and honey","Press into a lined pan","Drizzle melted chocolate, sprinkle seeds","Refrigerate 1 hour, cut into 8 bars"],
    tags:["meal-prep","energy","no-bake"] },
];

// ---- Generate TypeScript ----
let ts = `import { Recipe } from "../core/models/Recipe";
import { CATEGORIES } from "../core/constants/categories";

/**
 * NutriPilot Recipe Database
 *
 * 120 recipes across all meal types and diet styles.
 * Covers breakfast (30), lunch (30), dinner (30), snack (30).
 * All ingredient IDs reference the mockFoods database (food-001 through food-160).
 */

export const mockRecipes: Recipe[] = [\n`;

const catMap = {
  protein: "CATEGORIES.protein",
  grains: "CATEGORIES.grains",
  vegetables: "CATEGORIES.vegetables",
  fruits: "CATEGORIES.fruits",
  dairy: "CATEGORIES.dairy",
  fats: "CATEGORIES.fats",
  legumes: "CATEGORIES.legumes",
  snacks: "CATEGORIES.snacks",
  supplements: "CATEGORIES.supplements",
  others: "CATEGORIES.others",
};

for (let i = 0; i < recipes.length; i++) {
  const r = recipes[i];
  const isLast = i === recipes.length - 1;

  ts += `  {\n`;
  ts += `    id: "${r.id}",\n`;
  ts += `    name: "${r.name}",\n`;
  ts += `    mealType: "${r.meal}",\n`;
  ts += `    servings: ${r.serv},\n`;
  ts += `    prepTime: ${r.prep},\n`;
  ts += `    dietStyle: [${r.style.map(s => `"${s}"`).join(", ")}],\n`;
  ts += `    ingredients: [\n`;
  for (const ing of r.ing) {
    ts += `      { foodItemId: "${ing[0]}", name: "${ing[1]}", quantity: ${ing[2]}, unit: "${ing[3]}", category: ${catMap[ing[4]]} },\n`;
  }
  ts += `    ],\n`;
  ts += `    instructions: [\n`;
  for (const inst of r.inst) {
    ts += `      "${inst}",\n`;
  }
  ts += `    ],\n`;
  ts += `    tags: [${r.tags.map(t => `"${t}"`).join(", ")}]\n`;
  ts += `  }${isLast ? "" : ","}\n`;
}

ts += `];\n`;

writeFileSync(OUT, ts, "utf-8");
console.log(`✅ Generated ${recipes.length} recipes → src/data/mockRecipes.ts`);
